<a href="https://colab.research.google.com/github/leegyuhi/oooooooooooooh/blob/master/10_10_ch02_code_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2: Vectors, matrices and multidimensional arrays

Robert Johansson

Updated source code listings for Numerical Python - A Practical Techniques Approach for Industry (ISBN 978-1-484205-54-9).

Updator: Kee-Youn Yoo

In [0]:
import numpy as np # numpy를 약자 np로 불러옴

## The Numpy array object

In [0]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [0]:
type(data) # numpy array에는 같은 데이터 형식으로만 들어감 / 문자열만이거나 숫자형만이거나 / 하나를 문자열로 넣으면 다 문자열이 됨

numpy.ndarray

In [0]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
data.ndim # data dimension

2

In [0]:
data.shape # 3행 2열

(3, 2)

In [0]:
data.size 

6

In [0]:
data.dtype # 64비트 정수형

dtype('int64')

In [0]:
data.nbytes # 내가 쓴 byte / 6 byte 씩

48

## Data types

In [0]:
np.array([1, 2, 3], dtype=np.int) # data type 지정

array([1, 2, 3])

In [0]:
d1=np.array([1, 2, 3], dtype=np.float)

In [0]:
d1.dtype

dtype('float64')

In [0]:
np.array([1, 2, 3], dtype=np.complex) # 복소수로 데이터 저장

array([1.+0.j, 2.+0.j, 3.+0.j])

### Type casting

In [0]:
data = np.array([1, 2, 3], dtype=np.float)

In [0]:
data.dtype

dtype('float64')

In [0]:
data

array([1., 2., 3.])

In [0]:
data = np.array(data, dtype=np.int) # 정수형으로 바꿈

In [0]:
data.dtype

dtype('int64')

In [0]:
data

array([1, 2, 3])

*or*

In [0]:
data = np.array([1.6, 2, 3], dtype=np.float)

In [0]:
data.astype(np.int) # astype은 데이터를 바꾸는 함수

array([1, 2, 3])

### Type promotion

In [0]:
d1 = np.array([1, 2, 3], dtype=float)

In [0]:
d2 = np.array([1, 2, 3], dtype=complex)

In [0]:
d1 + d2 # 자동으로 d1을 complex 타입으로 바꿔서 더함

array([2.+0.j, 4.+0.j, 6.+0.j])

In [0]:
(d1 + d2).dtype

dtype('complex128')

### Type-depending operation

In [0]:
np.sqrt(np.array([-1, 0, 1])) # 제곱근, 정수형이었는데 실수형이 됨 / nan은 숫자가 아니라는 뜻

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [0]:
np.sqrt(np.array([-1, 0, 1], dtype=complex)) # 복소수형 지정하면 루트(-1)도 먹는다

array([0.+1.j, 0.+0.j, 1.+0.j])

### Real and imaginary parts 

In [0]:
data = np.array([1, 2, 3], dtype=complex); data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [0]:
data.real # 실수부만 찍어줌

array([1., 2., 3.])

In [0]:
data.imag # 허수부만

array([0., 0., 0.])

In [0]:
np.real(data)

array([1., 2., 3.])

In [0]:
np.imag(data)

array([0., 0., 0.])

### Order of array data in memory

행렬을 저장하는 방법에 대해서 column이나 row냐

Multidimensional arrays are stored as contiguous data in memory. Consider the case of a two-dimensional array, containing rows and columns: One possible way to store this array as a consecutive sequence of values is to store the rows after each other, and another equally valid approach is to store the columns one after another. The former is called row-major format and the latter is column-major format. Whether to use row-major or column-major is a matter of conventions, and the **row-major format** is used for example in the **C** programming language, and **Fortran** uses the **column-major format**. 

A `NumPy` array can be specified to be stored in row-major format, using the keyword argument `order='C'`, and column-major format, using the keyword argument `order='F'`, when the array is created or reshaped. The default format is *row-major*. 

In general, the `NumPy` array attribute `ndarray.strides` defines exactly how this mapping is done. The `strides` attribute is a tuple of the same length as the number of axes (dimensions) of the array. Each value in `strides` is the factor by which the index for the corresponding axis is multiplied when calculating the *memory offset (in bytes)* for a given index expression.

In [0]:
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

In [0]:
data.strides # 한 숫자당 4바이트 씩인데, 다음 줄의 데이타로 가려면 몇 바이트를 건너 뛰어야 하는가 (아래, 옆)

(12, 4)

In [0]:
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64, order='F') # 한 숫자당 8바이트 씩인데 저장 방법이 F라서 건너뛸 때 8바이트만

In [0]:
data.strides

(8, 16)

## Creating arrays

### Arrays created from lists and other array-like objects

In [0]:
data = np.array([1, 2, 3, 4])

In [0]:
data.ndim

1

In [0]:
data.shape # (1,4)라고 안 씀 / 헷갈리니깐 기억 잘 하자

(4,)

In [0]:
data = np.array([[1, 2], [3, 4]])

In [0]:
data.ndim

2

In [0]:
data.shape

(2, 2)

### Arrays filled with constant values

In [0]:
np.zeros((2, 3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones(4)

array([1., 1., 1., 1.])

---

In [0]:
data = np.ones(4)

In [0]:
data.dtype

dtype('float64')

In [0]:
data = np.ones(4, dtype=np.int64)

In [0]:
data.dtype

dtype('int64')

---

In [0]:
5.4 * np.ones(10)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [0]:
np.full(10, 5.4) # slightly more efficient

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

---

In [0]:
x1 = np.empty(5); x1.fill(3.0)

In [0]:
x1

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [0]:
np.arange(0, 11, 1) # 0부터 10까지 간격을 1씩

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
np.linspace(0, 10, 11) # generally recommended / lear space / 0부터 10까지 11 등분해라

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences 

In [0]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100 / 1부터 100까지 5등분 / 로그스케일로 그리면 직선

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh grid arrays

In [0]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

In [0]:
X, Y = np.meshgrid(x, y)

In [0]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [0]:
Y # X와 Y가 2차원 데이터 쌍이 된다 (x,y)

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [0]:
Z = (X + Y)**2; Z # 행렬에서의 제곱이 아님

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

### Creating uninitialized arrays

In [0]:
x = np.empty(8, dtype=np.float); x
# 8개짜리 메모리 자리를 만들어라, 숫자들은 걍 쓰레기 값

array([2.41054391e-316, 1.58101007e-322, 2.46151512e-312, 1.42560534e-071,
       5.19996650e-062, 4.08161379e-033, 9.14559501e-043, 2.26555601e-306])

### Creating arrays with properties of other arrays

In [0]:
def f(x):    
    y = np.ones_like(x)    # compute with x and y    
    return y

x = np.array([[1, 2, 3], [4, 5, 6]])
y = f(x); y

array([[1, 1, 1],
       [1, 1, 1]])

### Creating matrix arrays

In [0]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [0]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [0]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Indexing and slicing

### One-dimensional arrays

In [0]:
a = np.arange(0, 11); a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
a[0]

0

In [0]:
a[-1]

10

In [0]:
a[4]

4

---

In [0]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

---

In [0]:
a[:5]

array([0, 1, 2, 3, 4])

In [0]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [0]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

### Multidimensional arrays

In [0]:
f = lambda m, n: n +10*m

In [0]:
A = np.fromfunction(f, (6, 6), dtype=int); A # please search for numpy.fromfunction at google

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

---

In [0]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [0]:
A[1, :]  # the second raw

array([10, 11, 12, 13, 14, 15])

In [0]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [0]:
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [0]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [0]:
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

Subarrays that are extracted from arrays using slice operations are **alternative views** of the same underlying
array data. That is, they are arrays that refer to the same data in memory as the original array, but with a
different `strides` configuration. When elements in a view are assigned new values, the values of the original
array are therefore also updated. For example,

In [0]:
B = A[1:5, 1:5]; B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [0]:
B[:, :] = 0; A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

When **a copy rather than a view** is needed, the view can be copied explicitly by using
the `copy` method of the `ndarray` instance.

In [0]:
C = B[1:3, 1:3].copy(); C

array([[0, 0],
       [0, 0]])

In [0]:
C[:, :] = 1; C

array([[1, 1],
       [1, 1]])

In [0]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and boolean-valued indexing

In [0]:
A = np.linspace(0, 1, 11); A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [0]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [0]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

---

In [0]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [0]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

Unlike arrays created by using slices, **the arrays returned using fancy indexing and Boolean-valued
indexing are not views**, but rather new independent arrays.

In [0]:
A = np.arange(10)

In [0]:
indices = [2, 4, 6]

In [0]:
B = A[indices]

In [0]:
B[0] = -1; A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
A[indices] = -1; A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

---

In [0]:
A = np.arange(10)

In [0]:
B = A[A > 5]

In [0]:
B[0] = -1; A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
A[A > 5] = -1; A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

### Summery

<table>
<tr>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_01.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_02.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_03.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_04.svg?raw=1"></td>
</tr>
<tr>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_05.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_06.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_07.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_08.svg?raw=1"></td>
</tr>
<tr>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_09.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_10.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_11.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_indexing_12.svg?raw=1"></td>
</tr>
</table>

## Reshaping and resizing

Reshaping an array does not require modifying the underlying array data; it only changes in how the
data is interpreted, by redefining the array’s `strides` attribute.

In [0]:
data = np.array([[1, 2], [3, 4]])

In [0]:
data1 = np.reshape(data, (1, 4)); data1

array([[1, 2, 3, 4]])

In [0]:
data1[0, 1] = -1; data

array([[ 1, -1],
       [ 3,  4]])

In [0]:
data2 = data.reshape(4); data2

array([ 1, -1,  3,  4])

In [0]:
data2[1] = -2; data

array([[ 1, -2],
       [ 3,  4]])

---

In [0]:
data = np.array([[1, 2], [3, 4]])

In [0]:
data1 = np.ravel(data); data1

array([1, 2, 3, 4])

In [0]:
data1[0] = -1; data

array([[-1,  2],
       [ 3,  4]])

The `ndarray` method `flatten` perform the same function, but
returns a **copy** instead of a view.

In [0]:
data2 = data.flatten(); data2

array([-1,  2,  3,  4])

In [0]:
data2[0] = -2; data

array([[-1,  2],
       [ 3,  4]])

---

In [0]:
data = np.arange(0, 5); data.shape

(5,)

In [0]:
column = data[:, np.newaxis]; column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [0]:
column.shape

(5, 1)

In [0]:
row = data[np.newaxis, :]; row

array([[0, 1, 2, 3, 4]])

In [0]:
row.shape

(1, 5)

In [0]:
row[0, 0] = -1; data

array([-1,  1,  2,  3,  4])

In [0]:
np.expand_dims(data, axis=1)

array([[-1],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [0]:
np.expand_dims(data, axis=0)

array([[-1,  1,  2,  3,  4]])

---

In [0]:
data = np.arange(5); data

array([0, 1, 2, 3, 4])

In [0]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [0]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [0]:
data = data[:, np.newaxis]; data.shape

(5, 1)

In [0]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [0]:
data1 = np.array([[1, 2], [3, 4]])

In [0]:
data2 = np.array([[5, 6]])

In [0]:
np.concatenate((data1, data2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
np.concatenate((data1, data2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## Vectorized expressions

### Arithmetic operations

In [0]:
x = np.array([[1, 2], [3, 4]])

In [0]:
y = np.array([[5, 6], [7, 8]])

In [0]:
x + y

array([[ 6,  8],
       [10, 12]])

In [0]:
y - x

array([[4, 4],
       [4, 4]])

In [0]:
x * y

array([[ 5, 12],
       [21, 32]])

In [0]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

---

In [0]:
x * 2

array([[2, 4],
       [6, 8]])

In [0]:
2**x

array([[ 2,  4],
       [ 8, 16]])

In [0]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [0]:
(y / 2).dtype

dtype('float64')

---

<table>
<tr>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_broadcasting_1.svg?raw=1"></td>
</tr>
<tr>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_broadcasting_2.svg?raw=1"></td>
</tr>
<tr>
</table>

In [0]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([[1, 2], [3, 4]]) # 오류수정
x / y

array([[1., 1.],
       [1., 1.]])

In [0]:
z = np.array([[2, 4]]); z.shape

(1, 2)

In [0]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [0]:
zz = np.vstack((z, z)); zz

array([[2, 4],
       [2, 4]])

In [0]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

---

In [0]:
z = np.array([[2], [4]]); z.shape

(2, 1)

In [0]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [0]:
zz = np.concatenate([z, z], axis=1); zz

array([[2, 2],
       [4, 4]])

In [0]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

---

In [0]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
x = x + y  # x is reassigned to a new array

In [0]:
x += y  # the values of array x are updated in place

### Elementwise functions

In [0]:
x = np.linspace(-1, 1, 11); x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [0]:
y = np.sin(np.pi * x)

In [0]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [0]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
np.sin(x)**2 + np.cos(x)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

---

In [0]:
def heaviside(x):
    return 1 if x > 0 else 0

In [0]:
heaviside(-1)

0

In [0]:
heaviside(1.5)

1

In [0]:
x = np.linspace(-5, 5, 11)
heaviside(x)

ValueError: ignored

In [0]:
heaviside = np.vectorize(heaviside)
heaviside(x)

In [0]:
def heaviside(x):  # much better way
    return 1 * (x > 0)

heaviside(x)

### Aggregate functions

In [0]:
data = np.random.normal(size=(15, 15))

In [0]:
np.mean(data)

In [0]:
data.mean()

---

In [0]:
data = np.random.normal(size=(5, 10, 15))

In [0]:
data.sum(axis=0).shape

In [0]:
data.sum(axis=(0, 2)).shape

In [0]:
data.sum()

---

In [0]:
data = np.arange(1, 10).reshape(3, 3); data

In [0]:
data.sum()

In [0]:
data.sum(axis=0)

In [0]:
data.sum(axis=1)

<table>
<tr>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_aggregation_1.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_aggregation_2.svg?raw=1"></td>
<td><img src="https://github.com/SeoulTechPSE/EngNm/blob/master/figs/array_aggregation_3.svg?raw=1"></td>
</tr>
</table>

### Boolean arrays and conditional expressions

In [0]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [0]:
a < b

---

In [0]:
np.all(a < b)

In [0]:
np.any(a < b)

In [0]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding elements in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elements in b")
else:
    print("All elements in b are smaller than their corresponding elements in a")

---

In [0]:
x = np.array([-2, -1, 0, 1, 2])

In [0]:
x > 0

In [0]:
1 * (x > 0)

In [0]:
x * (x > 0)

---

In [0]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

#   return height *np.logical_and(x >= position, x <= (position + width))                                       

In [0]:
x = np.linspace(-5, 5, 11)

In [0]:
pulse(x, position=-2, height=1, width=5)

In [0]:
pulse(x, position=1, height=2, width=2)

---

In [0]:
x = np.linspace(-4, 4, 9)

In [0]:
np.where(x < 0, x**2, x**3)

In [0]:
np.select([x < -1, x < 2, x>= 2], [x**2, x**3, x**4])

In [0]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])

---

In [0]:
np.nonzero(abs(x) > 2)

In [0]:
x[np.nonzero(abs(x) > 2)]

In [0]:
x[abs(x) > 2]

### Set operations

In [0]:
a = np.unique([1, 2, 3, 3]); a

In [0]:
b = np.unique([2, 3, 4, 4, 5, 6, 5]); b

In [0]:
np.in1d(a, b)

In [0]:
1 in a

In [0]:
1 in b

In [0]:
np.all(np.in1d(a, b))  # to test if a is a subset of b

---

In [0]:
np.union1d(a, b)

In [0]:
np.intersect1d(a, b)

In [0]:
np.setdiff1d(a, b)

In [0]:
np.setdiff1d(b, a)

### Operations on arrays

In [0]:
data = np.arange(9).reshape(3, 3); data

In [0]:
np.transpose(data)

---

In [0]:
data = np.random.randn(1, 2, 3, 4, 5); data

In [0]:
data.shape

In [0]:
data.T.shape

## Matrix and vector operations

In [0]:
A = np.arange(1, 7).reshape(2, 3); A

In [0]:
B = np.arange(1, 7).reshape(3, 2); B

In [0]:
np.dot(A, B)

In [0]:
np.dot(B, A)

---

In [0]:
A = np.arange(9).reshape(3, 3); A

In [0]:
x = np.arange(3); x

In [0]:
np.dot(A, x)

In [0]:
A.dot(x)

---

In [0]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

In [0]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [0]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

---

In [0]:
A1 = np.matrix(A)
B1 = np.matrix(B)

In [0]:
Ap = B1 * A1 * B1.I

or

In [0]:
A2 = np.asmatrix(A)
B2 = np.asmatrix(B)

In [0]:
Ap = B2 * A2 * B2.I

In [0]:
Ap = np.asarray(Ap)

---

In [0]:
np.inner(x, x)

In [0]:
np.dot(x, x)

In [0]:
y = x[:, np.newaxis]; y

In [0]:
np.dot(y.T, y)

---

In [0]:
x = np.array([1, 2, 3])

In [0]:
np.outer(x, x)

In [0]:
np.kron(x, x)

In [0]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

In [0]:
np.kron(np.ones((2, 2)), np.identity(2))

In [0]:
np.kron(np.identity(2), np.ones((2, 2)))

---

In [0]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [0]:
np.einsum("n,n", x, y)

In [0]:
np.inner(x, y)

In [0]:
A = np.arange(9).reshape(3, 3)
B = A.T

In [0]:
np.einsum("mk,kn", A, B)

In [0]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

## Versions

In [0]:
%reload_ext version_information
%version_information numpy